apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echoserver.fullname" . }}
  labels:
    {{- include "echoserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 2 .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "echoserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "echoserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "echoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            # Kubernetes unnecessarily requiring quoting on numeric env vars #82296 
            - name: PORT
              value: {{ .Values.containerPort | quote }}
            - name: CUSTOME_ENV_VAR01
              value: "env var 01"
            - name: CUSTOME_ENV_VAR02
              value: "env var 02"
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            #{{- with .Values.ingress.annotations }}
            #annotations:
            #{{- toYaml . | nindent 4 }}
            #{{- end }}  
            # exposing pod info as env variables using k8s downward API for demo purposes
            # https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # exposing Helm info as env variables for demo purposes
            - name: HELM_CHART_NAME
              value: {{ .Chart.Name }} 
            - name: HELM_CHART_VERSION
              value: {{ .Chart.Version | quote }}
            - name: HELM_RELEASE
              value: {{ .Release.Name }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
