{{- if not (empty .Values.service) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echoserver.fullname" . }}
  labels:
    {{- include "echoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: {{ .Values.service.protocol }}
      name: helm-echoserver-main
  selector:
    {{- include "echoserver.selectorLabels" . | nindent 4 }}
{{- end}}